name: Lint and Format

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Ruff
        run: pip install ruff==0.3.7
      
      - name: Run Ruff linting
        run: ruff check .
      
      - name: Run Ruff formatting
        run: ruff format --check .
